// Project data structure with slugs, categories, and translations
export const projects = [
  {
    id: 1,
    slug: 'bukhara-airport',
    category: ['exterior'],
    titleKey: 'projects.airport.title',
    subtitleKey: 'projects.airport.subtitle',
    locationKey: 'projects.airport.location',
    descriptionKey: 'projects.airport.description',
    image: '/images/projects/1.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.airport.details',
    categoryKey: 'projects.airport.category',
    clientKey: 'projects.airport.client',
    statusKey: 'projects.airport.status',
    year: '2023',
    areaKey: 'projects.airport.area',
    typeOfWorkKey: 'projects.airport.typeOfWork',
    ideaKey: 'projects.airport.idea',
    technicalParamsKey: 'projects.airport.technicalParams',
    architectureKey: 'projects.airport.architecture',
    teamKey: 'projects.airport.team',
    exteriorKey: 'projects.airport.exterior',
    visualSymbolsKey: 'projects.airport.visualSymbols',
    numberOfFloorsKey: 'projects.airport.numberOfFloors',
    functionsKey: 'projects.airport.functions',
    servicesKey: 'projects.airport.services',
    internalZoneSeparationKey: 'projects.airport.internalZoneSeparation',
  },
  {
    id: 2,
    slug: 'business-center',
    category: ['exterior'],
    titleKey: 'projects.businessCenter.title',
    subtitleKey: 'projects.businessCenter.subtitle',
    locationKey: 'projects.businessCenter.location',
    descriptionKey: 'projects.businessCenter.description',
    image: '/images/projects/2.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.businessCenter.details',
    categoryKey: 'projects.businessCenter.category',
    clientKey: 'projects.businessCenter.client',
    statusKey: 'projects.businessCenter.status',
    year: '2022',
    areaKey: 'projects.businessCenter.area',
    typeOfWorkKey: 'projects.businessCenter.typeOfWork',
    ideaKey: 'projects.businessCenter.idea',
    technicalParamsKey: 'projects.businessCenter.technicalParams',
    architectureKey: 'projects.businessCenter.architecture',
    teamKey: 'projects.businessCenter.team',
    exteriorKey: 'projects.businessCenter.exterior',
    visualSymbolsKey: 'projects.businessCenter.visualSymbols',
    numberOfFloorsKey: 'projects.businessCenter.numberOfFloors',
    functionsKey: 'projects.businessCenter.functions',
    servicesKey: 'projects.businessCenter.services',
    internalZoneSeparationKey: 'projects.businessCenter.internalZoneSeparation',
  },
  {
    id: 3,
    slug: 'mirror-skyscraper',
    category: ['exterior'],
    titleKey: 'projects.skyscraper.title',
    subtitleKey: 'projects.skyscraper.subtitle',
    locationKey: 'projects.skyscraper.location',
    descriptionKey: 'projects.skyscraper.description',
    image: '/images/projects/3.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.skyscraper.details',
    categoryKey: 'projects.skyscraper.category',
    clientKey: 'projects.skyscraper.client',
    statusKey: 'projects.skyscraper.status',
    year: '2024',
    areaKey: 'projects.skyscraper.area',
    typeOfWorkKey: 'projects.skyscraper.typeOfWork',
    ideaKey: 'projects.skyscraper.idea',
    technicalParamsKey: 'projects.skyscraper.technicalParams',
    architectureKey: 'projects.skyscraper.architecture',
    teamKey: 'projects.skyscraper.team',
    exteriorKey: 'projects.skyscraper.exterior',
    visualSymbolsKey: 'projects.skyscraper.visualSymbols',
    numberOfFloorsKey: 'projects.skyscraper.numberOfFloors',
    functionsKey: 'projects.skyscraper.functions',
    servicesKey: 'projects.skyscraper.services',
    internalZoneSeparationKey: 'projects.skyscraper.internalZoneSeparation',
  },
  {
    id: 4,
    slug: 'freedom-tower',
    category: ['exterior'],
    titleKey: 'projects.freedomTower.title',
    subtitleKey: 'projects.freedomTower.subtitle',
    locationKey: 'projects.freedomTower.location',
    descriptionKey: 'projects.freedomTower.description',
    image: '/images/projects/4.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.freedomTower.details',
    categoryKey: 'projects.freedomTower.category',
    clientKey: 'projects.freedomTower.client',
    statusKey: 'projects.freedomTower.status',
    year: '2023',
    areaKey: 'projects.freedomTower.area',
    typeOfWorkKey: 'projects.freedomTower.typeOfWork',
    ideaKey: 'projects.freedomTower.idea',
    technicalParamsKey: 'projects.freedomTower.technicalParams',
    architectureKey: 'projects.freedomTower.architecture',
    teamKey: 'projects.freedomTower.team',
    exteriorKey: 'projects.freedomTower.exterior',
    visualSymbolsKey: 'projects.freedomTower.visualSymbols',
    numberOfFloorsKey: 'projects.freedomTower.numberOfFloors',
    functionsKey: 'projects.freedomTower.functions',
    servicesKey: 'projects.freedomTower.services',
    internalZoneSeparationKey: 'projects.freedomTower.internalZoneSeparation',
  },
  {
    id: 5,
    slug: 'luxury-residence',
    category: ['exterior'],
    titleKey: 'projects.luxuryResidence.title',
    subtitleKey: 'projects.luxuryResidence.subtitle',
    locationKey: 'projects.luxuryResidence.location',
    descriptionKey: 'projects.luxuryResidence.description',
    image: '/images/projects/1.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.luxuryResidence.details',
    categoryKey: 'projects.luxuryResidence.category',
    clientKey: 'projects.luxuryResidence.client',
    statusKey: 'projects.luxuryResidence.status',
    year: '2022',
    areaKey: 'projects.luxuryResidence.area',
    typeOfWorkKey: 'projects.luxuryResidence.typeOfWork',
    ideaKey: 'projects.luxuryResidence.idea',
    technicalParamsKey: 'projects.luxuryResidence.technicalParams',
    architectureKey: 'projects.luxuryResidence.architecture',
    teamKey: 'projects.luxuryResidence.team',
    exteriorKey: 'projects.luxuryResidence.exterior',
    visualSymbolsKey: 'projects.luxuryResidence.visualSymbols',
    numberOfFloorsKey: 'projects.luxuryResidence.numberOfFloors',
    functionsKey: 'projects.luxuryResidence.functions',
    servicesKey: 'projects.luxuryResidence.services',
    internalZoneSeparationKey: 'projects.luxuryResidence.internalZoneSeparation',
  },
  {
    id: 6,
    slug: 'modern-office-complex',
    category: ['exterior'],
    titleKey: 'projects.modernOffice.title',
    subtitleKey: 'projects.modernOffice.subtitle',
    locationKey: 'projects.modernOffice.location',
    descriptionKey: 'projects.modernOffice.description',
    image: '/images/projects/2.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.modernOffice.details',
    categoryKey: 'projects.modernOffice.category',
    clientKey: 'projects.modernOffice.client',
    statusKey: 'projects.modernOffice.status',
    year: '2023',
    areaKey: 'projects.modernOffice.area',
    typeOfWorkKey: 'projects.modernOffice.typeOfWork',
    ideaKey: 'projects.modernOffice.idea',
    technicalParamsKey: 'projects.modernOffice.technicalParams',
    architectureKey: 'projects.modernOffice.architecture',
    teamKey: 'projects.modernOffice.team',
    exteriorKey: 'projects.modernOffice.exterior',
    visualSymbolsKey: 'projects.modernOffice.visualSymbols',
    numberOfFloorsKey: 'projects.modernOffice.numberOfFloors',
    functionsKey: 'projects.modernOffice.functions',
    servicesKey: 'projects.modernOffice.services',
    internalZoneSeparationKey: 'projects.modernOffice.internalZoneSeparation',
  },
  {
    id: 7,
    slug: 'residential-interior',
    category: ['interior'],
    titleKey: 'projects.residentialInterior.title',
    subtitleKey: 'projects.residentialInterior.subtitle',
    locationKey: 'projects.residentialInterior.location',
    descriptionKey: 'projects.residentialInterior.description',
    image: '/images/projects/3.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.residentialInterior.details',
    categoryKey: 'projects.residentialInterior.category',
    clientKey: 'projects.residentialInterior.client',
    statusKey: 'projects.residentialInterior.status',
    year: '2024',
    areaKey: 'projects.residentialInterior.area',
    typeOfWorkKey: 'projects.residentialInterior.typeOfWork',
    ideaKey: 'projects.residentialInterior.idea',
    technicalParamsKey: 'projects.residentialInterior.technicalParams',
    architectureKey: 'projects.residentialInterior.architecture',
    teamKey: 'projects.residentialInterior.team',
    exteriorKey: 'projects.residentialInterior.exterior',
    visualSymbolsKey: 'projects.residentialInterior.visualSymbols',
    numberOfFloorsKey: 'projects.residentialInterior.numberOfFloors',
    functionsKey: 'projects.residentialInterior.functions',
    servicesKey: 'projects.residentialInterior.services',
    internalZoneSeparationKey: 'projects.residentialInterior.internalZoneSeparation',
  },
  {
    id: 8,
    slug: 'cultural-center',
    category: ['exterior'],
    titleKey: 'projects.culturalCenter.title',
    subtitleKey: 'projects.culturalCenter.subtitle',
    locationKey: 'projects.culturalCenter.location',
    descriptionKey: 'projects.culturalCenter.description',
    image: '/images/projects/4.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.culturalCenter.details',
    categoryKey: 'projects.culturalCenter.category',
    clientKey: 'projects.culturalCenter.client',
    statusKey: 'projects.culturalCenter.status',
    year: '2023',
    areaKey: 'projects.culturalCenter.area',
    typeOfWorkKey: 'projects.culturalCenter.typeOfWork',
    ideaKey: 'projects.culturalCenter.idea',
    technicalParamsKey: 'projects.culturalCenter.technicalParams',
    architectureKey: 'projects.culturalCenter.architecture',
    teamKey: 'projects.culturalCenter.team',
    exteriorKey: 'projects.culturalCenter.exterior',
    visualSymbolsKey: 'projects.culturalCenter.visualSymbols',
    numberOfFloorsKey: 'projects.culturalCenter.numberOfFloors',
    functionsKey: 'projects.culturalCenter.functions',
    servicesKey: 'projects.culturalCenter.services',
    internalZoneSeparationKey: 'projects.culturalCenter.internalZoneSeparation',
  },
  {
    id: 9,
    slug: 'commercial-interior',
    category: ['interior'],
    titleKey: 'projects.commercialInterior.title',
    subtitleKey: 'projects.commercialInterior.subtitle',
    locationKey: 'projects.commercialInterior.location',
    descriptionKey: 'projects.commercialInterior.description',
    image: '/images/projects/1.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.commercialInterior.details',
    categoryKey: 'projects.commercialInterior.category',
    clientKey: 'projects.commercialInterior.client',
    statusKey: 'projects.commercialInterior.status',
    year: '2022',
    areaKey: 'projects.commercialInterior.area',
    typeOfWorkKey: 'projects.commercialInterior.typeOfWork',
    ideaKey: 'projects.commercialInterior.idea',
    technicalParamsKey: 'projects.commercialInterior.technicalParams',
    architectureKey: 'projects.commercialInterior.architecture',
    teamKey: 'projects.commercialInterior.team',
    exteriorKey: 'projects.commercialInterior.exterior',
    visualSymbolsKey: 'projects.commercialInterior.visualSymbols',
    numberOfFloorsKey: 'projects.commercialInterior.numberOfFloors',
    functionsKey: 'projects.commercialInterior.functions',
    servicesKey: 'projects.commercialInterior.services',
    internalZoneSeparationKey: 'projects.commercialInterior.internalZoneSeparation',
  },
];

// Helper function to get project by slug
export const getProjectBySlug = (slug) => {
  return projects.find((project) => project.slug === slug);
};

// Helper function to get all projects
export const getAllProjects = () => {
  return projects;
};

