// Project data structure with slugs, categories, and translations
export const projects = [
  {
    id: 1,
    slug: 'bukhara-airport',
    category: ['exterior'],
    titleKey: 'projects.airport.title',
    locationKey: 'projects.airport.location',
    descriptionKey: 'projects.airport.description',
    image: '/images/projects/1.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.airport.details',
    categoryKey: 'projects.airport.category',
    clientKey: 'projects.airport.client',
    statusKey: 'projects.airport.status',
    year: '2023',
    areaKey: 'projects.airport.area',
    typeOfWorkKey: 'projects.airport.typeOfWork',
  },
  {
    id: 2,
    slug: 'business-center',
    category: ['exterior'],
    titleKey: 'projects.businessCenter.title',
    locationKey: 'projects.businessCenter.location',
    descriptionKey: 'projects.businessCenter.description',
    image: '/images/projects/2.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.businessCenter.details',
    categoryKey: 'projects.businessCenter.category',
    clientKey: 'projects.businessCenter.client',
    statusKey: 'projects.businessCenter.status',
    year: '2022',
    areaKey: 'projects.businessCenter.area',
    typeOfWorkKey: 'projects.businessCenter.typeOfWork',
  },
  {
    id: 3,
    slug: 'mirror-skyscraper',
    category: ['exterior'],
    titleKey: 'projects.skyscraper.title',
    locationKey: 'projects.skyscraper.location',
    descriptionKey: 'projects.skyscraper.description',
    image: '/images/projects/3.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.skyscraper.details',
    categoryKey: 'projects.skyscraper.category',
    clientKey: 'projects.skyscraper.client',
    statusKey: 'projects.skyscraper.status',
    year: '2024',
    areaKey: 'projects.skyscraper.area',
    typeOfWorkKey: 'projects.skyscraper.typeOfWork',
  },
  {
    id: 4,
    slug: 'freedom-tower',
    category: ['exterior'],
    titleKey: 'projects.freedomTower.title',
    locationKey: 'projects.freedomTower.location',
    descriptionKey: 'projects.freedomTower.description',
    image: '/images/projects/4.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.freedomTower.details',
    categoryKey: 'projects.freedomTower.category',
    clientKey: 'projects.freedomTower.client',
    statusKey: 'projects.freedomTower.status',
    year: '2023',
    areaKey: 'projects.freedomTower.area',
    typeOfWorkKey: 'projects.freedomTower.typeOfWork',
  },
  {
    id: 5,
    slug: 'luxury-residence',
    category: ['exterior'],
    titleKey: 'projects.luxuryResidence.title',
    locationKey: 'projects.luxuryResidence.location',
    descriptionKey: 'projects.luxuryResidence.description',
    image: '/images/projects/1.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.luxuryResidence.details',
    categoryKey: 'projects.luxuryResidence.category',
    clientKey: 'projects.luxuryResidence.client',
    statusKey: 'projects.luxuryResidence.status',
    year: '2022',
    areaKey: 'projects.luxuryResidence.area',
    typeOfWorkKey: 'projects.luxuryResidence.typeOfWork',
  },
  {
    id: 6,
    slug: 'modern-office-complex',
    category: ['exterior'],
    titleKey: 'projects.modernOffice.title',
    locationKey: 'projects.modernOffice.location',
    descriptionKey: 'projects.modernOffice.description',
    image: '/images/projects/2.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.modernOffice.details',
    categoryKey: 'projects.modernOffice.category',
    clientKey: 'projects.modernOffice.client',
    statusKey: 'projects.modernOffice.status',
    year: '2023',
    areaKey: 'projects.modernOffice.area',
    typeOfWorkKey: 'projects.modernOffice.typeOfWork',
  },
  {
    id: 7,
    slug: 'residential-interior',
    category: ['interior'],
    titleKey: 'projects.residentialInterior.title',
    locationKey: 'projects.residentialInterior.location',
    descriptionKey: 'projects.residentialInterior.description',
    image: '/images/projects/3.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.residentialInterior.details',
    categoryKey: 'projects.residentialInterior.category',
    clientKey: 'projects.residentialInterior.client',
    statusKey: 'projects.residentialInterior.status',
    year: '2024',
    areaKey: 'projects.residentialInterior.area',
    typeOfWorkKey: 'projects.residentialInterior.typeOfWork',
  },
  {
    id: 8,
    slug: 'cultural-center',
    category: ['exterior'],
    titleKey: 'projects.culturalCenter.title',
    locationKey: 'projects.culturalCenter.location',
    descriptionKey: 'projects.culturalCenter.description',
    image: '/images/projects/4.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.culturalCenter.details',
    categoryKey: 'projects.culturalCenter.category',
    clientKey: 'projects.culturalCenter.client',
    statusKey: 'projects.culturalCenter.status',
    year: '2023',
    areaKey: 'projects.culturalCenter.area',
    typeOfWorkKey: 'projects.culturalCenter.typeOfWork',
  },
  {
    id: 9,
    slug: 'commercial-interior',
    category: ['interior'],
    titleKey: 'projects.commercialInterior.title',
    locationKey: 'projects.commercialInterior.location',
    descriptionKey: 'projects.commercialInterior.description',
    image: '/images/projects/1.jpg',
    images: ['/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg','/images/projects/1.jpg', '/images/projects/2.jpg', '/images/projects/3.jpg'],
    detailsKey: 'projects.commercialInterior.details',
    categoryKey: 'projects.commercialInterior.category',
    clientKey: 'projects.commercialInterior.client',
    statusKey: 'projects.commercialInterior.status',
    year: '2022',
    areaKey: 'projects.commercialInterior.area',
    typeOfWorkKey: 'projects.commercialInterior.typeOfWork',
  },
];

// Helper function to get project by slug
export const getProjectBySlug = (slug) => {
  return projects.find((project) => project.slug === slug);
};

// Helper function to get all projects
export const getAllProjects = () => {
  return projects;
};

